[project]
name = "funcsolv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "starlingnia", email = "rahalinedophy@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "numpy>=2.5.3",
]

[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
funcsolv = "funcsolv:main"

[build-system]
requires = ["uv_build>=0.12.11,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-root = "src"
module-name = "FuncSolv"

